### ISSUE TITLE
gep tagged both not.monotonic.or.unknown and is.monotonic

### ISSUE THREAD

**Issue by hailinzeng** [bezerrathm/MonotonicLoopDetection#5]
C code:

    #include <stdlib.h>
    int main() {
      int size = 32 + rand()%10;
      int step = size % 8;
      char* str = new char[size];
      for (int i = 0; i + step < size; i+=step) {
        for (int j = 0; j < step; j++) {
          str[i+j] = str[i+j] + i + j;
        }
      }
      return 0;
    }

byte code:

      %arrayidx13 = getelementptr inbounds i8, i8* %call2, i64 %idxprom12, !dbg !50, !not.monotonic.or.unknown !29, !is.monotonic !29

**Comment by bezerrathm** [comment]
Fixed
